repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        types: [yaml]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        types: [python]
        args:
          [
            --ignore-missing-imports,
            --follow-imports=silent,
            --show-column-numbers,
            --no-strict-optional,
            --warn-redundant-casts,
            --warn-unused-ignores,
            --warn-return-any,
            --warn-unused-configs,
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
            --disallow-untyped-calls,
            --disallow-any-generics,
            --no-implicit-optional,
            --pretty,
          ]
